global:
  scrape_interval: 5s
  evaluation_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: docker
    static_configs:
    - targets: ["host.docker.interval:93233"]
    
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profile-service:8083']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8082']

  - job_name: 'item-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['item-service:8084']

  - job_name: 'cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cart-service:8086']

