server:
  port: 8080

jwt:
  secret: thisIsJwtKeyk212kjdjdjsajjk21k2k3k21llksalkaskaslddfjlkghxcljkzvberjbjhdsljjeehgjsadljfhjwhjhjsadfwesf
spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: api-gateway
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

