spring:

  kafka:
    bootstrap-servers: kafka:9092  # Only changed value

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # Only changed value

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka  # Only changed value

cors:
  allowed-origins:
    - http://angels.ge/
    - https://angels.ge/