spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres-cart:5432/cart_db  # Only changed value
    # username/password remain inherited from application.yml

  kafka:
    bootstrap-servers: kafka:9092  # Only changed value

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka  # Only changed value

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # Only changed value