# application.yml


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  application:
    name: item-service

  datasource:
    url: jdbc:postgresql://localhost:5432/item_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: item-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: item-service
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

kafka:
  topic:
    item-added: item.added

jwt:
  secret: thisIsJwtKeyk212kjdjdjsajjk21k2k3k21llksalkaskaslddfjlkghxcljkzvberjbjhdsljjeehgjsadljfhjwhjhjsadfwesf